### ISSUE TITLE
Unable to import stories

### ISSUE THREAD

**Issue by gr3tchel** [daterre/Cradle#85]
Hello,
if I import a story into unity, I get this error:

```
> Story compilation error at passage '': An assembly `System.Drawing' with the same identity has already been imported. Consider removing one of the references

	(code not available)

UnityEngine.Debug:LogErrorFormat(String, Object[])
Cradle.Editor.CradleAssetProcessor:OnPostprocessAllAssets(String[], String[], String[], String[])
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
```

and

```
The story diary_AB01.html has some errors and can't be imported (see console for details).
UnityEngine.Debug:LogErrorFormat(String, Object[])
Cradle.Editor.CradleAssetProcessor:OnPostprocessAllAssets(String[], String[], String[], String[])
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
```

I tried the fix the @mifozsky fix but it doesn't work. It only work if I switch API compatibility level from .NET standard 4.0 to .NET standard 2.0, and then delete the System.Drawning located in Asset/Plugin. However, this solution is unacceptable,because it causes some other errors, due to the missing reference. 
Is there a way to fix that?

**Comment by wilsonHodgson** [comment]
I tried the same same exact thing. I would love to see this work on 4.0, but I don't have time right now to help fix this issue. I also don't have an appropriate understanding of the system.
